<?php

namespace Acme\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MyUserTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyUserTestRepository extends EntityRepository
{
}
