parameters:
#    codeception.example.class: Dev\CodeceptionBundle\Example

services:
#    codeception.example:
#        class: %codeception.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
